/*
 * Chipper - an open polyglot game engine
 * Copyright (C) 2019-2020 the Chipper developers
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package com.playsawdust.chipper.client.gl;

import java.util.EnumSet;
import java.util.Locale;
import java.util.Map;

import org.checkerframework.checker.nullness.qual.Nullable;
import org.lwjgl.opengl.GL11;
import org.lwjgl.opengl.GL20;
import org.lwjgl.opengl.GL30;
import org.lwjgl.opengl.GL31;
import org.lwjgl.opengl.GL32;
import org.lwjgl.opengl.GL33;
import org.lwjgl.opengl.GL41;
import org.lwjgl.opengl.GL43;

import com.google.common.collect.ImmutableMap;

import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;

/**
 * Represents OpenGL constants which are valid for GL11::glGet, and whose "get" response yields either one integer value
 * or one symbolic constant value. Booleans are omitted from this enum, even though they are valid for integer "get"s.
 * 
 * <p>Note: Constants introduced after OpenGL 3.3 are also omitted from this list, because they describe a very large
 * space of extended state and are a huge pain to enter into the enum. These are however preserved as comments.
 */
public enum GLInteger { //TODO: Figure out mutability, then add this to pipeline state
	ACTIVE_TEXTURE      (13, GL20.GL_ACTIVE_TEXTURE),
	ARRAY_BUFFER_BINDING(15, GL20.GL_ARRAY_BUFFER_BINDING),
	BLEND_DST_ALPHA     (14, GL20.GL_BLEND_DST_ALPHA),
	BLEND_DST_RGB       (14, GL20.GL_BLEND_DST_RGB),
	BLEND_EQUATION_RGB  (20, GL20.GL_BLEND_EQUATION_RGB),
	BLEND_EQUATION_ALPHA(20, GL20.GL_BLEND_EQUATION_ALPHA),
	BLEND_SRC_ALPHA     (14, GL20.GL_BLEND_SRC_ALPHA),
	BLEND_SRC_RGB       (14, GL20.GL_BLEND_SRC_RGB),
	
	//GL43 Capabilities:
	MAX_COMPUTE_SHADER_STORAGE_BLOCKS(43, GL43.GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS),
	
	//.put("max_compute_shader_storage_blocks", GL43.GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS)
	//MAX_COMBINED_SHADER_STORAGE_BLOCKS
	//MAX_COMPUTE_UNIFORM_BLOCKS
	//MAX_COMPUTE_TEXTURE_IMAGE_UNITS
	//MAX_COMPUTE_UNIFORM_COMPONENTS
	//MAX_COMPUTE_ATOMIC_COUNTERS
	//MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS
	//MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS
	//MAX_COMPUTE_WORK_GROUP_INVOCATIONS
	//MAX_COMPUTE_WORK_GROUP_COUNT
	//MAX_COMPUTE_WORK_GROUP_SIZE
	//.put("dispatch_indirect_buffer_binding", GL43.GL_DISPATCH_INDIRECT_BUFFER_BINDING)
	//.put("", GL43.GL_MAX_DEBUG_GROUP_STACK_DEPTH)
	//DEBUG_GROUP_STACK_DEPTH
	
	CONTEXT_FLAGS                  (30, GL30.GL_CONTEXT_FLAGS),
	CULL_FACE_MODE                 (11, GL11.GL_CULL_FACE_MODE),
	CURRENT_PROGRAM                (20, GL20.GL_CURRENT_PROGRAM),
	DEPTH_CLEAR_VALUE              (11, GL11.GL_DEPTH_CLEAR_VALUE),
	DEPTH_FUNC                     (11, GL11.GL_DEPTH_FUNC),
	DRAW_BUFFER                    (11, GL11.GL_DRAW_BUFFER),
	//DRAW_BUFFER_0 through DRAW_BUFFER_15 are skipped here
	DRAW_FRAMEBUFFER_BINDING       (30, GL30.GL_DRAW_FRAMEBUFFER_BINDING),
	READ_FRAMEBUFFER_BINDING       (30, GL30.GL_READ_FRAMEBUFFER_BINDING),
	ELEMENT_ARRAY_BUFFER_BINDING   (15, GL20.GL_ELEMENT_ARRAY_BUFFER_BINDING),
	FRAGMENT_SHADER_DERIVATIVE_HINT(20, GL20.GL_FRAGMENT_SHADER_DERIVATIVE_HINT),
	//IMPLEMENTATION_COLOR_READ_FORMAT(GL43.GL_IMPLEMENTATION_COLOR_READ_FORMAT),
	//IMPLEMENTATION_COLOR_READ_TYPE(GL43.GL_IMPLEMENTATION_COLOR_READ_TYPE),
	LINE_SMOOTH_HINT               (11, GL11.GL_LINE_SMOOTH_HINT),
	LINE_WIDTH                     (11, GL11.GL_LINE_WIDTH),
	//LAYER_PROVOKING_VERTEX(GL43.GL_LAYER_PROVOKING_VERTEX),
	LOGIC_OP_MODE                  (11, GL11.GL_LOGIC_OP_MODE),
	MAJOR_VERSION                  (30, GL30.GL_MAJOR_VERSION),
	MAX_3D_TEXTURE_SIZE            (12, GL20.GL_MAX_3D_TEXTURE_SIZE),
	MAX_ARRAY_TEXTURE_SIZE         (30, GL30.GL_MAX_ARRAY_TEXTURE_LAYERS),
	MAX_CLIP_DISTANCES             (30, GL30.GL_MAX_CLIP_DISTANCES),
	MAX_COLOR_TEXTURE_SAMPLES      (32, GL32.GL_MAX_COLOR_TEXTURE_SAMPLES),
	//MAX_COMBINED_ATOMIC_COUNTERS(GL43.GL_MAX_COMBINED_ATOMIC_COUNTERS),
	//MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS(GL43.GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS),
	//MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS
	MAX_COMBINED_TEXTURE_IMAGE_UNITS      (20, GL20.GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS),
	MAX_COMBINED_UNIFORM_BLOCKS           (31, GL31.GL_MAX_COMBINED_UNIFORM_BLOCKS),
	MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS(31, GL31.GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS),
	MAX_CUBE_MAP_TEXTURE_SIZE             (13, GL20.GL_MAX_CUBE_MAP_TEXTURE_SIZE),
	MAX_DEPTH_TEXTURE_SAMPLES             (32, GL32.GL_MAX_DEPTH_TEXTURE_SAMPLES),
	MAX_DRAW_BUFFERS                      (20, GL20.GL_MAX_DRAW_BUFFERS),
	MAX_DUAL_SOURCE_DRAW_BUFFERS          (33, GL33.GL_MAX_DUAL_SOURCE_DRAW_BUFFERS),
	MAX_ELEMENTS_INDICES                  (12, GL20.GL_MAX_ELEMENTS_INDICES),
	MAX_ELEMENTS_VERTICES                 (12, GL20.GL_MAX_ELEMENTS_VERTICES),
	//MAX_FRAGMENT_ATOMIC_COUNTERS(GL43.GL_MAX_FRAGMENT_ATOMIC_COUNTERS),
	//MAX_FRAGMENT_SHADER_STORAGE_BLOCKS
	//MAX_FRAGMENT_INPUT_COMPONENTS
	//MAX_FRAGMENT_UNIFORM_COMPONENTS
	//MAX_FRAGMENT_UNIFORM_VECTORS
	//MAX_FRAGMENT_UNIFORM_BLOCKS
	//MAX_FRAMEBUFFER_WIDTH(GL43.GL_MAX_FRAMEBUFFER_WIDTH),
	//MAX_FRAMEBUFFER_HEIGHT
	//MAX_FRAMEBUFFER_LAYERS
	//MAX_FRAMEBUFFER_SAMPLES
	//MAX_GEOMETRY_ATOMIC_COUNTERS
	//MAX_GEOMETRY_SHADER_STORAGE_BLOCKS
	//MAX_GEOMETRY_INPUT_COMPONENTS
	//MAX_GEOMETRY_OUTPUT_COMPONENTS
	//MAX_GEOMETRY_TEXTURE_IMAGE_UNITS
	//MAX_GEOMETRY_UNIFORM_BLOCKS
	//MAX_GEOMETRY_UNIFORM_COMPONENTS
	MAX_INTEGER_SAMPLES            (32, GL32.GL_MAX_INTEGER_SAMPLES),
	//MIN_MAP_BUFFER_ALIGNMENT(GL43.GL_MIN_MAP_BUFFER_ALIGNMENT),
	//MAX_LABEL_LENGTH(GL43.GL_MAX_LABEL_LENGTH),
	MAX_PROGRAM_TEXEL_OFFSET       (30, GL30.GL_MAX_PROGRAM_TEXEL_OFFSET),
	MIN_PROGRAM_TEXEL_OFFSET       (30, GL30.GL_MIN_PROGRAM_TEXEL_OFFSET),
	MAX_RECTANGLE_TEXTURE_SIZE     (31, GL31.GL_MAX_RECTANGLE_TEXTURE_SIZE),
	MAX_RENDERBUFFER_SIZE          (30, GL30.GL_MAX_RENDERBUFFER_SIZE),
	MAX_SAMPLE_MASK_WORDS          (32, GL32.GL_MAX_SAMPLE_MASK_WORDS),
	MAX_SERVER_WAIT_TIMEOUT        (32, GL32.GL_MAX_SERVER_WAIT_TIMEOUT),
	//MAX_SHADER_STORAGE_BUFFER_BINDINGS(GL43.GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS),
	//MAX_TESS_CONTROL_ATOMIC_COUNTERS
	//MAX_TESS_EVALUATION_ATOMIC_COUNTERS
	//MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS
	//MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS
	MAX_TEXTURE_BUFFER_SIZE        (31, GL31.GL_MAX_TEXTURE_BUFFER_SIZE),
	MAX_TEXTURE_IMAGE_UNITS        (20, GL20.GL_MAX_TEXTURE_IMAGE_UNITS),
	MAX_TEXTURE_LOD_BIAS           (14, GL20.GL_MAX_TEXTURE_LOD_BIAS),
	MAX_TEXTURE_SIZE               (11, GL11.GL_MAX_TEXTURE_SIZE),
	MAX_UNIFORM_BUFFER_BINDINGS    (31, GL31.GL_MAX_UNIFORM_BUFFER_BINDINGS),
	MAX_UNIFORM_BLOCK_SIZE         (31, GL31.GL_MAX_UNIFORM_BLOCK_SIZE),
	MAX_UNIFORM_LOCATIONS          (43, GL43.GL_MAX_UNIFORM_LOCATIONS),
	MAX_VARYING_COMPONENTS         (30, GL30.GL_MAX_VARYING_COMPONENTS),
	MAX_VARYING_VECTORS            (41, GL43.GL_MAX_VARYING_VECTORS),
	MAX_VARYING_FLOATS             (20, GL20.GL_MAX_VARYING_FLOATS),
	//MAX_VERTEX_ATOMIC_COUNTERS
	MAX_VERTEX_ATTRIBS             (20, GL20.GL_MAX_VERTEX_ATTRIBS),
	//MAX_VERTEX_SHADER_STORAGE_BLOCKS
	MAX_VERTEX_TEXTURE_IMAGE_UNITS (20, GL20.GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS),
	MAX_VERTEX_UNIFORM_COMPONENTS  (20, GL20.GL_MAX_VERTEX_UNIFORM_COMPONENTS),
	MAX_VERTEX_UNIFORM_VECTORS     (41, GL41.GL_MAX_VERTEX_UNIFORM_VECTORS),
	MAX_VERTEX_OUTPUT_COMPONENTS   (32, GL32.GL_MAX_VERTEX_OUTPUT_COMPONENTS),
	MAX_VERTEX_UNIFORM_BLOCKS      (31, GL31.GL_MAX_VERTEX_UNIFORM_BLOCKS),
	MAX_VIEWPORTS                  (41, GL41.GL_MAX_VIEWPORTS),
	MINOR_VERSION                  (30, GL30.GL_MINOR_VERSION),
	NUM_COMPRESSED_TEXTURE_FORMATS (13, GL20.GL_NUM_COMPRESSED_TEXTURE_FORMATS),
	NUM_EXTENSIONS                 (30, GL30.GL_NUM_EXTENSIONS),
	NUM_PROGRAM_BINARY_FORMATS     (41, GL41.GL_NUM_PROGRAM_BINARY_FORMATS),
	NUM_SHADER_BINARY_FORMATS      (41, GL41.GL_NUM_SHADER_BINARY_FORMATS),
	PACK_ALIGNMENT                 (11, GL11.GL_PACK_ALIGNMENT),
	PACK_IMAGE_HEIGHT              (12, GL20.GL_PACK_IMAGE_HEIGHT),
	PACK_LSB_FIRST                 (11, GL20.GL_PACK_LSB_FIRST),
	PACK_ROW_LENGTH                (11, GL11.GL_PACK_ROW_LENGTH),
	PACK_SKIP_IMAGES               (12, GL20.GL_PACK_SKIP_IMAGES),
	PACK_SKIP_PIXELS               (11, GL11.GL_PACK_SKIP_PIXELS),
	PACK_SKIP_ROWS                 (11, GL11.GL_PACK_SKIP_ROWS),
	PIXEL_PACK_BUFFER_BINDING      (21, GL30.GL_PIXEL_PACK_BUFFER_BINDING),
	PIXEL_UNPACK_BUFFER_BINDING    (21, GL30.GL_PIXEL_UNPACK_BUFFER_BINDING),
	POINT_FADE_THRESHOLD_SIZE      (14, GL20.GL_POINT_FADE_THRESHOLD_SIZE),
	PRIMITIVE_RESTART_INDEX        (31, GL31.GL_PRIMITIVE_RESTART_INDEX),
	PROGRAM_PIPELINE_BINDING       (41, GL43.GL_PROGRAM_PIPELINE_BINDING),
	PROVOKING_VERTEX               (32, GL32.GL_PROVOKING_VERTEX),
	POINT_SIZE                     (11, GL11.GL_POINT_SIZE),
	POINT_SIZE_GRANULARITY         (11, GL11.GL_POINT_SIZE_GRANULARITY),
	POLYGON_OFFSET_FACTOR          (11, GL11.GL_POLYGON_OFFSET_FACTOR),
	POLYGON_OFFSET_UNITS           (11, GL11.GL_POLYGON_OFFSET_UNITS),
	POLYGON_SMOOTH_HINT            (11, GL11.GL_POLYGON_SMOOTH_HINT),
	READ_BUFFER                    (11, GL11.GL_READ_BUFFER),
	RENDERBUFFER_BINDING           (30, GL30.GL_RENDERBUFFER_BINDING),
	SAMPLE_BUFFERS                 (13, GL30.GL_SAMPLE_BUFFERS),
	SAMPLER_BINDING                (33, GL33.GL_SAMPLER_BINDING),
	SAMPLES                        (13, GL20.GL_SAMPLES),
	SHADER_STORAGE_BUFFER_BINDING  (43, GL43.GL_SHADER_STORAGE_BUFFER_BINDING),
	SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT (43, GL43.GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT),
	SMOOTH_LINE_WIDTH_GRANULARITY  (12, GL20.GL_SMOOTH_LINE_WIDTH_GRANULARITY),
	STENCIL_BACK_FAIL              (20, GL20.GL_STENCIL_BACK_FAIL),
	STENCIL_BACK_FUNC              (20, GL20.GL_STENCIL_BACK_FUNC),
	STENCIL_BACK_PASS_DEPTH_FAIL   (20, GL20.GL_STENCIL_BACK_PASS_DEPTH_FAIL),
	STENCIL_BACK_PASS_DEPTH_PASS   (11, GL11.GL_STENCIL_PASS_DEPTH_PASS),
	STENCIL_BACK_REF               (20, GL20.GL_STENCIL_BACK_REF),
	STENCIL_BACK_VALUE_MASK        (20, GL20.GL_STENCIL_BACK_VALUE_MASK),
	STENCIL_BACK_WRITEMASK         (20, GL20.GL_STENCIL_BACK_WRITEMASK),
	STENCIL_CLEAR_VALUE            (11, GL11.GL_STENCIL_CLEAR_VALUE),
	STENCIL_FAIL                   (11, GL11.GL_STENCIL_FAIL),
	STENCIL_FUNC                   (11, GL11.GL_STENCIL_FUNC),
	STENCIL_PASS_DEPTH_FAIL        (11, GL11.GL_STENCIL_PASS_DEPTH_FAIL),
	STENCIL_PASS_DEPTH_PASS        (11, GL11.GL_STENCIL_PASS_DEPTH_PASS),
	STENCIL_REF                    (11, GL11.GL_STENCIL_REF),
	STENCIL_VALUE_MASK             (11, GL11.GL_STENCIL_VALUE_MASK),
	STENCIL_WRITEMASK              (11, GL11.GL_STENCIL_WRITEMASK),
	SUBPIXEL_BITS                  (11, GL11.GL_SUBPIXEL_BITS),
	TEXTURE_BINDING_1D             (11, GL11.GL_TEXTURE_BINDING_1D),
	TEXTURE_BINDING_1D_ARRAY       (30, GL30.GL_TEXTURE_BINDING_1D_ARRAY),
	TEXTURE_BINDING_2D             (11, GL11.GL_TEXTURE_BINDING_2D),
	TEXTURE_BINDING_2D_ARRAY       (30, GL30.GL_TEXTURE_BINDING_2D_ARRAY),
	TEXTURE_BINDING_2D_MULTISAMPLE (32, GL32.GL_TEXTURE_BINDING_2D_MULTISAMPLE),
	TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY (32, GL32.GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY),
	TEXTURE_BINDING_3D             (12, GL20.GL_TEXTURE_BINDING_3D),
	TEXTURE_BINDING_BUFFER         (31, GL31.GL_TEXTURE_BINDING_BUFFER), // Mysteriously appears twice in Khronos docs, seems to do double duty for glBindTexxture with target GL_TEXTURE_BUFFER and glBindBuffer
	TEXTURE_BINDING_CUBE_MAP       (13, GL20.GL_TEXTURE_BINDING_CUBE_MAP),
	TEXTURE_BINDING_RECTANGLE      (31, GL31.GL_TEXTURE_BINDING_RECTANGLE),
	TEXTURE_COMPRESSION_HINT       (13, GL20.GL_TEXTURE_COMPRESSION_HINT),
	TEXTURE_BUFFER_OFFSET_ALIGNMENT(43, GL43.GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT),
	TIMESTAMP                      (33, GL33.GL_TIMESTAMP),
	TRANSFORM_FEEDBACK_BUFFER_BINDING(30, GL30.GL_TRANSFORM_FEEDBACK_BUFFER_BINDING), // This is GL30? We could do REALLY FAST PARTICLES with this!
	UNIFORM_BUFFER_BINDING         (31, GL31.GL_UNIFORM_BUFFER_BINDING),
	UNIFORM_BUFFER_OFFSET_ALIGNMENT(31, GL31.GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT),
	UNPACK_ALIGNMENT               (11, GL11.GL_UNPACK_ALIGNMENT),
	UNPACK_IMAGE_HEIGHT            (12, GL20.GL_UNPACK_IMAGE_HEIGHT),
	UNPACK_ROW_LENGTH              (11, GL11.GL_UNPACK_ROW_LENGTH),
	UNPACK_SKIP_IMAGES             (12, GL20.GL_UNPACK_SKIP_IMAGES),
	UNPACK_SKIP_PIXELS             (11, GL11.GL_UNPACK_SKIP_PIXELS),
	UNPACK_SKIP_ROWS               (11, GL11.GL_PACK_SKIP_ROWS),
	VERTEX_ARRAY_BINDING           (30, GL30.GL_VERTEX_ARRAY_BINDING),
	VERTEX_BINDING_DIVISOR         (43, GL43.GL_VERTEX_BINDING_DIVISOR),
	VERTEX_BINDING_OFFSET          (43, GL43.GL_VERTEX_BINDING_OFFSET),
	VERTEX_BINDING_STRIDE          (43, GL43.GL_VERTEX_BINDING_STRIDE),
	MAX_VERTEX_ATTRIB_RELATIVE_OFFSET(43, GL43.GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET),
	MAX_VERTEX_ATTRIB_BINDINGS     (43, GL43.GL_MAX_VERTEX_ATTRIB_BINDINGS),
	VIEWPORT_INDEX_PROVOKING_VERTEX(41, GL43.GL_VIEWPORT_INDEX_PROVOKING_VERTEX),
	VIEWPORT_SUBPIXEL_BITS         (41, GL43.GL_VIEWPORT_SUBPIXEL_BITS),
	MAX_ELEMENT_INDEX              (43, GL43.GL_MAX_ELEMENT_INDEX)
	;
	
	private static Int2ObjectMap<GLInteger> REVERSE_LOOKUP = new Int2ObjectOpenHashMap<>();
	static {
		for(GLInteger i : values()) {
			REVERSE_LOOKUP.put(i.value, i);
		}
	}
	
	public static final EnumSet<GLInteger> CONSTANT_ATTRIBUTES = EnumSet.of(
			MAJOR_VERSION, MINOR_VERSION,
			MAX_COMBINED_TEXTURE_IMAGE_UNITS, MAX_COMBINED_UNIFORM_BLOCKS, MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS, MAX_CUBE_MAP_TEXTURE_SIZE,
			MAX_DEPTH_TEXTURE_SAMPLES, MAX_DRAW_BUFFERS, MAX_DUAL_SOURCE_DRAW_BUFFERS, MAX_ELEMENTS_INDICES, MAX_ELEMENTS_VERTICES, MAX_INTEGER_SAMPLES,
			MAX_PROGRAM_TEXEL_OFFSET, MIN_PROGRAM_TEXEL_OFFSET, MAX_RECTANGLE_TEXTURE_SIZE, MAX_RENDERBUFFER_SIZE, MAX_SAMPLE_MASK_WORDS,
			MAX_SERVER_WAIT_TIMEOUT, MAX_TEXTURE_BUFFER_SIZE, MAX_TEXTURE_IMAGE_UNITS, MAX_TEXTURE_LOD_BIAS, MAX_TEXTURE_SIZE,
			MAX_UNIFORM_BUFFER_BINDINGS, MAX_UNIFORM_BLOCK_SIZE, MAX_VARYING_COMPONENTS, MAX_VARYING_FLOATS, MAX_VERTEX_ATTRIBS,
			MAX_TEXTURE_IMAGE_UNITS, MAX_VERTEX_UNIFORM_COMPONENTS, NUM_COMPRESSED_TEXTURE_FORMATS, NUM_EXTENSIONS, POINT_SIZE_GRANULARITY,
			SUBPIXEL_BITS, MAX_COMPUTE_SHADER_STORAGE_BLOCKS, MAX_VERTEX_ATTRIB_RELATIVE_OFFSET, MAX_VERTEX_ATTRIB_BINDINGS, MAX_ELEMENT_INDEX
		);
	
	
	private final int minVersion;
	private final int value;
	
	GLInteger(int value) {
		this.value = value;
		this.minVersion = 11;
	}
	
	GLInteger(int minVersion, int value) {
		this.value = value;
		this.minVersion = minVersion;
	}
	
	public int glConstant() {
		return value;
	}
	
	public int minimumVersion() {
		return minVersion;
	}
	
	public int query() {
		return GL11.glGetInteger(value);
	}
	
	public static Map<String, Integer> queryAll() {
		ImmutableMap.Builder<String, Integer> result = ImmutableMap.<String, Integer>builder();
		for(GLInteger prop: values()) {
			result.put(prop.name().toLowerCase(Locale.ROOT), prop.query());
		}
		return result.build();
	}
	
	@Nullable
	public static final GLInteger forConstant(int value) {
		return REVERSE_LOOKUP.get(value);
	}
}
